// <auto-generated />
using System;
using CropTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CropTrack.Migrations
{
    [DbContext(typeof(FieldDbTrackContext))]
    [Migration("20260513173001_AddProduceKnowledgeBase")]
    partial class AddProduceKnowledgeBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CropTrack.Models.Crop", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropId"));

                    b.Property<int>("AvgGrowthDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OptimalTemperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("YieldPerAcre")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CropId");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("CropTrack.Models.Farmer", b =>
                {
                    b.Property<int>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("FarmerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("CropTrack.Models.Field", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldId"));

                    b.Property<decimal>("Acres")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("FieldId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("RegionId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("CropTrack.Models.FieldCrop", b =>
                {
                    b.Property<int>("FieldCropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldCropId"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlantingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("QuantityInTons")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FieldCropId");

                    b.HasIndex("CropId");

                    b.HasIndex("FieldId");

                    b.ToTable("FieldCrops");
                });

            modelBuilder.Entity("CropTrack.Models.MarketPrice", b =>
                {
                    b.Property<int>("MarketPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarketPriceId"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PricePerTon")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MarketPriceId");

                    b.HasIndex("CropId");

                    b.ToTable("MarketPrices");
                });

            modelBuilder.Entity("CropTrack.Models.Produce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvgDaysToHarvest")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IdealTempC")
                        .HasColumnType("float");

                    b.Property<double>("MaxPh")
                        .HasColumnType("float");

                    b.Property<double>("MaxTempC")
                        .HasColumnType("float");

                    b.Property<double>("MinPh")
                        .HasColumnType("float");

                    b.Property<double>("MinTempC")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PlantingDepthCm")
                        .HasColumnType("float");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SpacingCm")
                        .HasColumnType("float");

                    b.Property<string>("WaterIntensity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvgDaysToHarvest = 75,
                            Category = "Fruit Vegetable",
                            IdealTempC = 24.0,
                            MaxPh = 6.7999999999999998,
                            MaxTempC = 35.0,
                            MinPh = 6.0,
                            MinTempC = 13.0,
                            Name = "Tomato",
                            PlantingDepthCm = 0.59999999999999998,
                            ScientificName = "Solanum lycopersicum",
                            SpacingCm = 50.0,
                            WaterIntensity = "High"
                        },
                        new
                        {
                            Id = 2,
                            AvgDaysToHarvest = 95,
                            Category = "Vegetable",
                            IdealTempC = 18.0,
                            MaxPh = 6.5,
                            MaxTempC = 30.0,
                            MinPh = 5.0,
                            MinTempC = 8.0,
                            Name = "Potato",
                            PlantingDepthCm = 10.0,
                            ScientificName = "Solanum tuberosum",
                            SpacingCm = 30.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            AvgDaysToHarvest = 75,
                            Category = "Vegetable",
                            IdealTempC = 18.0,
                            MaxPh = 6.7999999999999998,
                            MaxTempC = 30.0,
                            MinPh = 6.0,
                            MinTempC = 7.0,
                            Name = "Carrot",
                            PlantingDepthCm = 1.0,
                            ScientificName = "Daucus carota",
                            SpacingCm = 8.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 4,
                            AvgDaysToHarvest = 50,
                            Category = "Vegetable",
                            IdealTempC = 17.0,
                            MaxPh = 7.0,
                            MaxTempC = 24.0,
                            MinPh = 6.0,
                            MinTempC = 4.0,
                            Name = "Lettuce",
                            PlantingDepthCm = 0.5,
                            ScientificName = "Lactuca sativa",
                            SpacingCm = 25.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 5,
                            AvgDaysToHarvest = 45,
                            Category = "Vegetable",
                            IdealTempC = 16.0,
                            MaxPh = 7.5,
                            MaxTempC = 24.0,
                            MinPh = 6.5,
                            MinTempC = 4.0,
                            Name = "Spinach",
                            PlantingDepthCm = 1.5,
                            ScientificName = "Spinacia oleracea",
                            SpacingCm = 10.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 6,
                            AvgDaysToHarvest = 55,
                            Category = "Fruit Vegetable",
                            IdealTempC = 27.0,
                            MaxPh = 7.0,
                            MaxTempC = 35.0,
                            MinPh = 6.0,
                            MinTempC = 16.0,
                            Name = "Cucumber",
                            PlantingDepthCm = 2.0,
                            ScientificName = "Cucumis sativus",
                            SpacingCm = 45.0,
                            WaterIntensity = "High"
                        },
                        new
                        {
                            Id = 7,
                            AvgDaysToHarvest = 80,
                            Category = "Fruit Vegetable",
                            IdealTempC = 24.0,
                            MaxPh = 6.7999999999999998,
                            MaxTempC = 32.0,
                            MinPh = 6.0,
                            MinTempC = 15.0,
                            Name = "Bell Pepper",
                            PlantingDepthCm = 0.59999999999999998,
                            ScientificName = "Capsicum annuum",
                            SpacingCm = 45.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 8,
                            AvgDaysToHarvest = 110,
                            Category = "Vegetable",
                            IdealTempC = 20.0,
                            MaxPh = 6.7999999999999998,
                            MaxTempC = 30.0,
                            MinPh = 6.0,
                            MinTempC = 7.0,
                            Name = "Onion",
                            PlantingDepthCm = 1.5,
                            ScientificName = "Allium cepa",
                            SpacingCm = 10.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 9,
                            AvgDaysToHarvest = 180,
                            Category = "Vegetable",
                            IdealTempC = 18.0,
                            MaxPh = 7.0,
                            MaxTempC = 30.0,
                            MinPh = 6.0,
                            MinTempC = 5.0,
                            Name = "Garlic",
                            PlantingDepthCm = 4.0,
                            ScientificName = "Allium sativum",
                            SpacingCm = 12.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 10,
                            AvgDaysToHarvest = 90,
                            Category = "Vegetable",
                            IdealTempC = 17.0,
                            MaxPh = 7.5,
                            MaxTempC = 24.0,
                            MinPh = 6.0,
                            MinTempC = 7.0,
                            Name = "Cabbage",
                            PlantingDepthCm = 1.0,
                            ScientificName = "Brassica oleracea var. capitata",
                            SpacingCm = 45.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 11,
                            AvgDaysToHarvest = 80,
                            Category = "Vegetable",
                            IdealTempC = 18.0,
                            MaxPh = 7.0,
                            MaxTempC = 24.0,
                            MinPh = 6.0,
                            MinTempC = 7.0,
                            Name = "Broccoli",
                            PlantingDepthCm = 1.0,
                            ScientificName = "Brassica oleracea var. italica",
                            SpacingCm = 45.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 12,
                            AvgDaysToHarvest = 85,
                            Category = "Vegetable",
                            IdealTempC = 18.0,
                            MaxPh = 7.0,
                            MaxTempC = 24.0,
                            MinPh = 6.0,
                            MinTempC = 7.0,
                            Name = "Cauliflower",
                            PlantingDepthCm = 1.0,
                            ScientificName = "Brassica oleracea var. botrytis",
                            SpacingCm = 50.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 13,
                            AvgDaysToHarvest = 85,
                            Category = "Fruit Vegetable",
                            IdealTempC = 27.0,
                            MaxPh = 6.7999999999999998,
                            MaxTempC = 35.0,
                            MinPh = 5.5,
                            MinTempC = 18.0,
                            Name = "Eggplant",
                            PlantingDepthCm = 0.59999999999999998,
                            ScientificName = "Solanum melongena",
                            SpacingCm = 60.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 14,
                            AvgDaysToHarvest = 55,
                            Category = "Vegetable",
                            IdealTempC = 22.0,
                            MaxPh = 7.0,
                            MaxTempC = 30.0,
                            MinPh = 6.0,
                            MinTempC = 12.0,
                            Name = "Green Bean",
                            PlantingDepthCm = 2.5,
                            ScientificName = "Phaseolus vulgaris",
                            SpacingCm = 12.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 15,
                            AvgDaysToHarvest = 65,
                            Category = "Vegetable",
                            IdealTempC = 16.0,
                            MaxPh = 7.5,
                            MaxTempC = 24.0,
                            MinPh = 6.0,
                            MinTempC = 5.0,
                            Name = "Pea",
                            PlantingDepthCm = 3.0,
                            ScientificName = "Pisum sativum",
                            SpacingCm = 7.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 16,
                            AvgDaysToHarvest = 105,
                            Category = "Grain",
                            IdealTempC = 24.0,
                            MaxPh = 7.0,
                            MaxTempC = 35.0,
                            MinPh = 5.7999999999999998,
                            MinTempC = 10.0,
                            Name = "Maize",
                            PlantingDepthCm = 4.0,
                            ScientificName = "Zea mays",
                            SpacingCm = 25.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 17,
                            AvgDaysToHarvest = 120,
                            Category = "Grain",
                            IdealTempC = 18.0,
                            MaxPh = 7.5,
                            MaxTempC = 32.0,
                            MinPh = 6.0,
                            MinTempC = 4.0,
                            Name = "Wheat",
                            PlantingDepthCm = 3.0,
                            ScientificName = "Triticum aestivum",
                            SpacingCm = 15.0,
                            WaterIntensity = "Low"
                        },
                        new
                        {
                            Id = 18,
                            AvgDaysToHarvest = 120,
                            Category = "Grain",
                            IdealTempC = 27.0,
                            MaxPh = 7.0,
                            MaxTempC = 35.0,
                            MinPh = 5.5,
                            MinTempC = 16.0,
                            Name = "Rice",
                            PlantingDepthCm = 2.0,
                            ScientificName = "Oryza sativa",
                            SpacingCm = 20.0,
                            WaterIntensity = "High"
                        },
                        new
                        {
                            Id = 19,
                            AvgDaysToHarvest = 105,
                            Category = "Grain Legume",
                            IdealTempC = 24.0,
                            MaxPh = 7.0,
                            MaxTempC = 35.0,
                            MinPh = 6.0,
                            MinTempC = 10.0,
                            Name = "Soybean",
                            PlantingDepthCm = 3.5,
                            ScientificName = "Glycine max",
                            SpacingCm = 20.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 20,
                            AvgDaysToHarvest = 100,
                            Category = "Oilseed",
                            IdealTempC = 23.0,
                            MaxPh = 7.5,
                            MaxTempC = 35.0,
                            MinPh = 6.0,
                            MinTempC = 10.0,
                            Name = "Sunflower",
                            PlantingDepthCm = 2.5,
                            ScientificName = "Helianthus annuus",
                            SpacingCm = 30.0,
                            WaterIntensity = "Medium"
                        },
                        new
                        {
                            Id = 21,
                            AvgDaysToHarvest = 90,
                            Category = "Fruit",
                            IdealTempC = 20.0,
                            MaxPh = 6.7999999999999998,
                            MaxTempC = 30.0,
                            MinPh = 5.5,
                            MinTempC = 8.0,
                            Name = "Strawberry",
                            PlantingDepthCm = 1.5,
                            ScientificName = "Fragaria × ananassa",
                            SpacingCm = 35.0,
                            WaterIntensity = "Medium"
                        });
                });

            modelBuilder.Entity("CropTrack.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("CropTrack.Models.WeatherLog", b =>
                {
                    b.Property<int>("WeatherLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeatherLogId"));

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Forecast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rainfall")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WeatherLogId");

                    b.HasIndex("RegionId");

                    b.ToTable("WeatherLogs");
                });

            modelBuilder.Entity("CropTrack.Models.Field", b =>
                {
                    b.HasOne("CropTrack.Models.Farmer", "Farmer")
                        .WithMany("Fields")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CropTrack.Models.Region", "Region")
                        .WithMany("Fields")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("CropTrack.Models.FieldCrop", b =>
                {
                    b.HasOne("CropTrack.Models.Crop", "Crop")
                        .WithMany("FieldCrops")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CropTrack.Models.Field", "Field")
                        .WithMany("FieldCrops")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("CropTrack.Models.MarketPrice", b =>
                {
                    b.HasOne("CropTrack.Models.Crop", "Crop")
                        .WithMany("MarketPrices")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("CropTrack.Models.WeatherLog", b =>
                {
                    b.HasOne("CropTrack.Models.Region", "Region")
                        .WithMany("WeatherLogs")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("CropTrack.Models.Crop", b =>
                {
                    b.Navigation("FieldCrops");

                    b.Navigation("MarketPrices");
                });

            modelBuilder.Entity("CropTrack.Models.Farmer", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("CropTrack.Models.Field", b =>
                {
                    b.Navigation("FieldCrops");
                });

            modelBuilder.Entity("CropTrack.Models.Region", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("WeatherLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
